name = "paste"
compatibility_date = "2023-01-28"
main = "src/index.js"

# config for default production environment
vars = { ENVIRONMENT = "production" }

kv_namespaces = [
  { binding = "PB", id = "fab15884d97342889a0c85afa651f297" }
]

